### PR TITLE
CIP-0052 | Add public keys to auditor table

### PR DESCRIPTION
**Pull request by simonjohnthompson**
Added field for public key information for auditors. This to be used to verify signed audit certification metadata.

### CODE REVIEW

**Review by rphair — COMMENTED** [review]
@simonjohnthompson it's good to have that extra field in the table for sure... but is this PR complete without those keys filled in?  If not, should this PR be kept in abeyance until those keys are added in further commits?

**Comment by L-as** [comment]
We should definitely add the public keys first. I suppose we can just comment in this PR.

**Comment by rphair** [comment]
> I suppose we can just comment on this PR.

sure @L-as if they're posted here in a way that allows editors to verify their validity (e.g. from the auditor's GitHub account), we can commit them if the PR author hasn't done so already.

**Comment by rphair** [comment]
@L-as @simonjohnthompson is [the last commit](https://github.com/cardano-foundation/CIPs/pull/406/commits/97cdc70d1c652a95136afd6030982de4f9c31f31) clear enough according to how people will be using the table?

**Comment by L-as** [comment]
I'd say so.

**Comment by KtorZ** [comment]
Suggestion: public keys here may be added over time by a representative of each relevant party, with a commit signed by the respective private key and from an account that belongs to the party's organization. 

How does that sound?

**Review by SebastienGllmt — APPROVED** [review]
Makes sense. Not sure there is a reason to block this PR waiting for other entities to add something. They can just make a followup PR if they want to

**Review by KtorZ — APPROVED** [review]

**Comment by L-as** [comment]
> Suggestion: public keys here may be added over time by a representative of each relevant party, with a commit signed by the respective private key and from an account that belongs to the party's organization.
> 
> How does that sound?

It's not sound. There's a cyclic dependency. s/signed commit/PR by member of org/.

**Comment by KtorZ** [comment]
> There's a cyclic dependency. 

What do you mean? 

- Alice puts key in the file. 
- Alice commits and signs the change with corresponding private key
- Alice opens a PR

where's the cycle exactly?

**Comment by L-as** [comment]
That only tells us that the owner of the key consented, not that the owner is the correct one.

**Comment by KtorZ** [comment]
Hence the second part: "and from an account that belongs to the party's organization"

**Pull request merged**
