### PR TITLE
CIP-???? | Blueprint NFT

### PR DESCRIPTION
**Pull request by AdmiralOOM**

### CODE REVIEW

**Review by rphair — COMMENTED** [review]
@AdmiralOOM apparently this is a follow-up from https://forum.cardano.org/t/cardano-improvement-proposals-cips-tutorial-series/120721/2.

I've put this in Draft mode while you attend to the many ways in which this does not conform to the requirements of [CIP-0001](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0001/README.md) (as I also suggested in that thread).  The most urgent change you need to make, leaving any reviewers unable to read your proposal properly until you do, is:
- rename your content to `README.md`
- move it into a temporary subdirectory name like `CIP-blueprint-NFT` (you can also use a generic directory name like your current `CIP-????` or `CIP-XXXX`

**Comment by AdmiralOOM** [comment]
@rphair Sorry, I am not so proficient in using Github. A bit of a learning curve here ^.^
(still trying to figure out how to create subdirectory :p )
Anyway my plan was to use this first CIP draft for creating an understanding of where we are heading with all of these functions. 
As we could not use cardano forum for the discussion.
Please let me know if something needs to be edited away.

**Comment by rphair** [comment]
@AdmiralOOM as I said [here](https://forum.cardano.org/t/cardano-improvement-proposals-cips-tutorial-series/120721/3), the Cardano Forum _is exactly_ the place for peer review of CIP drafts before posting them on GitHub. 🤓  You will still have to attend to the format issues if continuing on GitHub, but in the meantime others may help as they've help with other CIP drafts to work on the scope and content.

Your current markup is OK to just copy into a thread, in this category like I [recommended](https://forum.cardano.org/t/cardano-improvement-proposals-cips-tutorial-series/120721) (https://forum.cardano.org/c/developers/cips/122).  For the meantime I'll leave this up as a Draft; if no progress or if it is ruled out as a potential CIP (by consensus, including yours) then we can close this PR.

**Comment by rphair** [comment]
@AdmiralOOM I'm changing the title back to what I had set it to before your reversion in https://github.com/cardano-foundation/CIPs/pull/580#event-10079384105... we need to have standardised, descriptive titles in our list of PRs.

**Comment by rphair** [comment]
@AdmiralOOM this PR came up for Triage at the biweekly CIP editors' meeting today: this sets set expectations about the next steps for a potential CIP.  The discussion noted that placeholders for CIPs are not the intended purpose of the PR queue on the CIPs repository.

We also concurred that you might have considered it important to post this material before the Project Catalyst Fund 10 submission & voting process.  If this is the case then please keep in mind that the CIP process should be kept separate from funding issues or any presentations to third parties.

Most of all our initial review emphasised that an eligible CIP should focus on documented methods of use to unaffiliated developers, rather than simply documenting one's own methods.  

Please keep all this mind and consider updating this proposal to a proper CIP soon.  We agreed to give it "a few more weeks" and I'm marking it `Waiting for Author` pending a properly written submission.  If you need more time than that, work on whatever CIP material you have should be done outside of GitHub e.g. on the several Cardano Forum threads you've already created for this material.

**Review by rphair — COMMENTED** [review]
@AdmiralOOM this PR came up for Triage at the biweekly CIP editors' meeting today: this sets set expectations about the next steps for a potential CIP.  The discussion noted that placeholders for CIPs are not the intended purpose of the PR queue on the CIPs repository.

We also concurred that you might have considered it important to post this material before the Project Catalyst Fund 10 submission & voting process.  If this is the case then please keep in mind that the CIP process should be kept separate from funding issues or any presentations to third parties.

Most of all our initial review emphasised that an eligible CIP should focus on documented methods of use to unaffiliated developers, rather than simply documenting one's own methods. 

Please keep all this mind and consider updating this proposal to a proper CIP soon.  We agreed to give it "a few more weeks" and I'm marking it `Waiting for Author` pending a properly written submission.  If you need more time than that, work on whatever CIP material you have should be done outside of GitHub e.g. on the several Cardano Forum threads you've already created for this material.

**Comment by rphair** [comment]
CIP meeting # 74 today concurred to close this PR due to author abandonment but I'll wait for @Ryun1 @Crypto2099 @SebastienGllmt to do so.

**Comment by Ryun1** [comment]
@AdmiralOOM 

Please be welcome to reopen the pull request if you intend to pursue this proposal, but please first attempt to move it into a format that more resembles a CIP or CPS.

**Pull request closed without merging**
