### PR TITLE
Update top-level README: post meeting #93

### PR DESCRIPTION
**Pull request by rphair**
Merged:
- https://github.com/cardano-foundation/CIPs/pull/841

Promoted:
- https://github.com/cardano-foundation/CIPs/pull/758
- https://github.com/cardano-foundation/CIPs/pull/857

Deprecated & Resubmitted:
- OLD https://github.com/cardano-foundation/CIPs/pull/780
- NEW https://github.com/cardano-foundation/CIPs/pull/862

Abandoned:
- https://github.com/cardano-foundation/CIPs/pull/269
- https://github.com/cardano-foundation/CIPs/pull/276
- https://github.com/cardano-foundation/CIPs/pull/314
- https://github.com/cardano-foundation/CIPs/pull/440

### CODE REVIEW

**Review by Ryun1 — APPROVED** [review]
great work!

**Comment by rphair** [comment]
Hopefully we will get a confirmation for the CIP-0128? title before merging (still pending https://github.com/cardano-foundation/CIPs/pull/758#discussion_r1690204699), but if still inconclusive I'm happy to merge this as it stands & modify it later if necessary.

**Review by Ryun1 — APPROVED** [review]

**Comment by Ryun1** [comment]
and https://github.com/cardano-foundation/CIPs/pull/857 assigned `129` (according to files changed) :)

**Comment by rphair** [comment]
> assigned/promoted `129` (according to files changed) :)

@Ryun1 thanks; as far as I can tell that being missing was a copy/paste error from my offline draft.  I've added it now to the manifest above.

**Review by Crypto2099 — APPROVED** [review]
All looks good to me.

**Pull request merged**
