### PR TITLE
CIP-9999 | Add mandatory Copyright + related cleanup

### LINKED ISSUE #759: CIP-9999 | How to add Copyright to CPSs
I have a PR half-created for this and ran into a stumbling block I hadn't considered in my https://github.com/cardano-foundation/CIPs/pull/756#issuecomment-1925794686 ... that if a Copyright section for CPSs were optional then we'd also have our first optional field in YAML headers since CIP-0001 was "reworked".

I don't think this is a problem syntactically, but it's all the more reason to first settle the recently proposed licensing question for CPSs according to which of these 3 options to take:

1. Do **nothing**: keep our current state of CPSs not having a Copyright section and generally covered by no open source licensing agreements.
1. Make CPS licensing **optional**: introducing it as an _optional section_ as recently added to CIP-9999... only requiring that it be the final section & sticking to 1 of the 2 licenses declared acceptable all along for CIPs (generally CC for documentation, Apache for code).
1. Make CPS licensing **mandatory**: simpler for syntax in both the CIP-9999 text and a universal YAML header field for every CPS.

Personally I don't see a universal need for mandatory open source licensing for CPSs unless the issues of warranty disclaimer and liability are considered.  Technically CIP editors as well as CPS authors and related CIP implementors would be included in liability scope unless someone can demonstrate otherwise.

What I don't know is what discussion preceded the current default of no licensing for CPSs: including why the CPS was excluded from the requirements imposed on the CIP.  This is my last specific request to @KtorZ and associates (@michaelpj?) & if no response then perhaps no particular investigation or discussion preceded this current question & we can consider all options anew.

Anyone with the means to present this to an appropriate legal authority, please do so.

Once we decide which of the 3 options above to take I have a PR half-written to cover it... though any particular suggestions of method & wording would be welcome here. 😎

### PR DESCRIPTION
**Pull request by rphair**
Fixes #759.

In addition to mimicking the CIP licensing requirements for the CPS, this removes static `LICENSE` files from the CIPs that still had them in spite of the fact that linking the license in the document footer is (and is preferred to be) sufficient for license binding.  (It also fixes that license link in one case that I missed in #389 "Remediation")

It might be less work to do the CPS license updates as part of this PR, but I think not because:
- some CPS authors will want to consider CC vs. Apache, and others might by default leave that choice to editors
- we could want to coordinate this with parsers for the Dev Portal and `cips.cardano.org` since currently undefined YAML header data might trigger warnings / errors / inappropriate formatting.  cc @KtorZ @katomm

### CODE REVIEW

**Comment by Ryun1** [comment]
Do we want to add a `License` field to the CPS header?

**Comment by rphair** [comment]
@Ryun1 you've spotted an interesting problem which I guess had always been a bother & didn't discover till now.  All along, the CIP has had `License` in the CIP header but has a `Copyright` section in the document.  I believe this is proper... but I reflected the duplicate term when calling it `Copyright` in the description of the front matter data.  I'll fix that now.

**Comment by rphair** [comment]
OK @Ryun1 TL;DR last 2 comments: oversight you pointed out is fixed in https://github.com/cardano-foundation/CIPs/pull/762/commits/ed51527a4ca40932cf9d7e2ed889c8756106b929

**Review by Crypto2099 — APPROVED** [review]
Looks good

**Comment by rphair** [comment]
yes & thanks @Ryun1 ... currently it's the same:

https://github.com/rphair/CIPs/blob/9463c113323ef0bebf55b5310bca2cc2cba17935/CIP-0001/README.md#header-preamble
> License 	Abbreviation of an approved license(s)

https://github.com/rphair/CIPs/blob/9463c113323ef0bebf55b5310bca2cc2cba17935/CIP-9999/README.md#header-preamble
> License 	Abbreviation of an approved license(s)

**Comment by Ryun1** [comment]
ahh sorry! I meant also in the template file

**Comment by rphair** [comment]
@Ryun1 likewise they are also currently the same in the last section (except for `CIP` vs `CPS`:

- https://raw.githubusercontent.com/rphair/CIPs/9463c113323ef0bebf55b5310bca2cc2cba17935/.github/CIP-TEMPLATE.md
- https://raw.githubusercontent.com/rphair/CIPs/9463c113323ef0bebf55b5310bca2cc2cba17935/.github/CPS-TEMPLATE.md

**Comment by Ryun1** [comment]
ah i am being silly!
sorry!

**Comment by Ryun1** [comment]
Wait, am I being silly?
I cant see the `License` in the CPS yaml header. I can see it in the document sections but not the header.

so the header would be:
```
---
CPS: ?
Title: ?
Status: Open
Category: ?
Authors:
    - John Doe <john.doe@email.domain>
Proposed Solutions: []
Discussions:
    - https://github.com/cardano-foundation/CIPs/pull/?
Created: YYYY-MM-DD
License: CC-BY-4.0
---
```

**Comment by rphair** [comment]
@Ryun1 you are not being silly but the purpose of this PR (posted in https://github.com/cardano-foundation/CIPs/pull/762#issue-2125011185) is deliberately __not__ to modify any CPS headers for [my own] worry that it will break downstream tooling & could well require some coordination beyond the editorial "rules" set in this PR:
> It might be less work to do the CPS license updates as part of this PR, but I think not because ... we could want to coordinate this with parsers for the Dev Portal and cips.cardano.org since currently undefined YAML header data might trigger warnings / errors / inappropriate formatting.

**Comment by rphair** [comment]
> License: CC-BY-4.0

OK @Ryun1 - done and done in https://github.com/cardano-foundation/CIPs/pull/762/commits/ee096be047a79a1ede12644c367bd696cfa539c9 I hope 😅

**Review by Ryun1 — APPROVED** [review]

**Pull request merged**
