### PR TITLE
CIP Editor Nomination: Adam Dean

### PR DESCRIPTION
**Pull request by Crypto2099**
Hello,

My name is Adam Dean. I am the co-founder of Buffy Bot Publishing, NFTxLV (formerly cNFTcon), Drip Dropz and several other projects and initiatives on the Cardano blockchain. I am a co- or principal author of several CIPs and am passionate about bringing well-defined standards to the Cardano ecosystem.

I am humbly nominating myself to serve as one of our community CIP Editors moving forward in the future to help shoulder some of the burden.

I am happy to answer any questions, comments, or concerns that you may have prior to my acceptance.

### CODE REVIEW

**Review by Ryun1 — APPROVED** [review]
Hey @Crypto2099,

I would be happy to welcome you to the CIP editors. I believe you have consistently demonstrated that you are a highly proficient member of the Cardano community and thus you would be of great benefit to the editors'.

+Don't forget to add your name to  the editors table on the top-level repository's README as well 😎

**Review by rphair — COMMENTED** [review]
welcome @Crypto2099 & likewise with what @Ryun1 said... I'm happy to sign off on this as well ✔️ (though would wait until we give all other editors a chance to post a review before merging) but first add a change to this table in your own PR branch: https://github.com/cardano-foundation/CIPs/tree/master#editors

Yes I know it's not very good decomposition that the identical data is stored in 2 places, but it looks better than linking to a separate document with just the CIP editors in it 🤓

**Review by rphair — APPROVED** [review]

**Review by KtorZ — APPROVED** [review]
Sounds reasonable to me.

**Review by SebastienGllmt — APPROVED** [review]

**Comment by rphair** [comment]
OK we are all in then.  Welcome @Crypto2099 🤠

**Pull request merged**
