### PR TITLE
CIP-0102 | Reference Implementation

### PR DESCRIPTION
**Pull request by SamDelaney**
A reference implementation for CIP-0102 royalties, written in Lucid (offchain) and Aiken (onchain).

In this reference implementation you'll find examples of:
- Minting a CIP 102 compliant NFT with royalties
- Validators for storing royalty metadata
  - Always Fails (royalty cannot be modified)
  - Reducible (royalty cannot be increased, but can be decreased)
- Reading a CIP 102 NFT’s royalties off chain
- Reading and validating against CIP 102 NFT royalties on chain

This code has not been audited and is **NOT INTENDED FOR PRODUCTION**, but to provide code examples of expected behavior.

### CODE REVIEW

**Comment by SamDelaney** [comment]
I still have some cleanup for clarity and consistency to be done here, and may dabble in some optimizations; however, it's now fully featured & ready for review by interested parties who don't mind digging through some sub-optimal code. Feedback is very welcome :)

I will mark as ready for merge when I'm satisfied with my sanitization.

**Comment by SamDelaney** [comment]
@rphair I was not aware of that decision, thanks for letting me know! No links necessary, I trust you 😄

I'll move my code to another repo & update this PR accordingly.

**Comment by SamDelaney** [comment]
Moved the code I had here to a new repo as requested. I can include my disclaimers about production readiness & general lack of polish in that repo, so I see no reason to delay this PR. Marking as ready for review & merge.

**Comment by rphair** [comment]
> @SamDelaney https://github.com/cardano-foundation/CIPs/pull/848#issuecomment-2195772602: @rphair I was not aware of that decision, thanks for letting me know! No links necessary, I trust you 😄

Thanks for your trust but I thought [recalling incorrectly] that one of the outcomes of that past deliberation was to update CIP-0001 (and now that I think about it, CIP-9999) with this reservation.  I'll submit a change request in the near future which will have the additional advantage of the 3 currently active editors unanimously confirming both this policy & the language used to express it.  cc @Crypto2099 @Ryun1

**Review by rphair — COMMENTED** [review]
Will be happy to approve this because it just updates the Path to Active along with the link to the completed reference implementation.  It looks like it's getting very close to `Active` status now (but **not** there yet; please anyone correct me if this appears incorrect).

Will sign off on this once the empty file & directory are removed under `ref_impl`.

**Comment by SamDelaney** [comment]
@rphair I think you may have misread the files changed. TODO.md was already included in the last PR so I'm just removing it here.

Here's [the current state of the CIP-102 subdirectory](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0102), and here's [what I'm updating it to with this PR](https://github.com/ikigai-github/CIPs/tree/cip102-refimpl/CIP-0102).

**Review by rphair — APPROVED** [review]
thanks @SamDelaney, I didn't misread the files changed... I just temporarily forgot how `git` works 🤪

**Review by Ryun1 — APPROVED** [review]
LGTM!

thanks for the update @SamDelaney

**Comment by rphair** [comment]
Marked `Last Check` so we can merge at Tuesday's meeting (or before then) once @Crypto2099 can also give it a look: https://hackmd.io/@cip-editors/92

**Review by Crypto2099 — APPROVED** [review]
These changes make sense and it's good to see the external links to the reference implementation so that can be iterated on asynchronously from the CIP Editors workflow.

**Comment by rphair** [comment]
taking off agenda & merging then, since unanimous 🚀

**Pull request merged**
