### PR TITLE
(adding clarifications to CIP-0001) | "Path to 'Active'" 

### PR DESCRIPTION
**Pull request by crptmppt**
Clarify "Path to 'Active'" so CIPs can be moved to 'Proposed'

### CODE REVIEW

**Review by KtorZ — APPROVED** [review]

**Comment by KtorZ** [comment]
Shall we also update the template and base sections to explicitly request a **Path to active** section?

**Comment by KtorZ** [comment]
Shall we also update the template and base sections to explicitly request a **Path to active** section?

**Comment by KtorZ** [comment]
@SebastienGllmt @rphair may I kindly ask you for approval on that one (unless you strongly oppose this change). Doing some book-keeping and noticed this was still open :s !

**Review by SebastienGllmt — APPROVED** [review]

**Review by rphair — COMMENTED** [review]
@KtorZ late to the party (still on other side of the world) but for the record this looks good to me 😎

**Pull request merged**
