### PR TITLE
CIP-0013 | Extend URI scheme with single stake pool links [proposal of update]

### PR DESCRIPTION
**Pull request by nicarq**
Hello CIP editors!

I know that the next CIP meeting is today, so in order to be able to make it in time, I created this PR on top of the work of @rphair. 

Why?

- Fixes the usage of the terminology stake (it should be delegate). Users delegate to stakepools, and stakepools are the ones that stake.
- 
- To make this more friendly to future extension of URI, I updated it the parameter key names are always passed. In the future, we could have more advance features that would require the usage of parameter names and it will look strange that sometimes we enforce that for some actions (delegate) and for others don't.

### CODE REVIEW

**Comment by rphair** [comment]
@nicarq the first point is true on general principle, but since staking is done from the node rather than any front end, the authority prefix `stake` unambiguously refers to delegation to a stake pool.

For long term consistency the question is whether that prefix should be a noun or a verb... **delegate** is the more appropriate verb and **stake** (short for *stake pool* reference) is the more appropriate noun.

From a user perspective I can confirm the prefix `stake` would be more readily understood and adopted by the community, based on the frequency of *delegate* vs. *stake* in the unofficial literature and social networking.

**Comment by nicarq** [comment]
Thanks for answering! In the wallets we are using delegation and not staking. The uri is to work with the wallets and not the nodes, so it would make sense to use delegate

**Comment by rphair** [comment]
There are three possibilities as I see it (full explanation in https://github.com/cardano-foundation/CIPs/pull/61#issuecomment-782141931):

1. **my opinion:** These changes remain unimplemented, since they're unnecessary if not undesirable.
2. **something I'd happily live with:** These changes are submitted as another PR relative to the resulting CIP-0013 (closing this PR) after https://github.com/cardano-foundation/CIPs/pull/61 is merged.
3. **if https://github.com/cardano-foundation/CIPs/pull/61 cannot proceed otherwise:** These changes are edited into https://github.com/cardano-foundation/CIPs/pull/61 to break the apparent deadlock.

**Comment by crptmppt** [comment]
@nicarq @rphair - it would be great if either or both of you can join [our next CIP meeting](https://www.crowdcast.io/e/cip-editors-meeting-17) to summarize/review the state of things.

**Comment by rphair** [comment]
Since it looks like CIP statuses are being checked before the meeting, please let me suggest these criteria for including this PR with CIP-0013.  I'll try to phrase these so this PR can be considered independently of https://github.com/cardano-foundation/CIPs/pull/61:

I believe the 2 changes above were suggested with single pool links only in mind: one blocking expansion into weighted multi-pool links, and the other presenting a nomenclature problem.  Therefore this PR should not be accepted unless the following questions can be answered, perhaps at the meeting:

* How will the use of a stake pool as a value (rather than a key) allow that stake pool term itself to have a value (in a weighted multi-pool URI)?
* How is the use of the word "delegate" (to indicate a stake pool) appropriate for stake pool links not being used for delegation (i.e. informative or analytical, especially applicable to a multi-pool "delegation portfolio")?

**Comment by crptmppt** [comment]
@nicarq - This PR has been sitting on the side for some time - can we get some clarifications re: last questions? ([discussion](https://github.com/cardano-foundation/CIPs/blob/master/BiweeklyMeetings/03-16-2021.md))

There's an expectation of considering both 61 and 65 as feasible, but it feels this once might be missing content as  noted in the discussion/notes from last meeting.

**Comment by crptmppt** [comment]
This PR has been tabled for now - will be brought up to the meeting if someone picks it up - but is not an active conversation currently

**Pull request closed without merging**
