### PR TITLE
Update top-level README: post meeting #80

### PR DESCRIPTION
**Pull request by rphair**
Promoted to CIP candidate:
- https://github.com/cardano-foundation/CIPs/pull/733
- https://github.com/cardano-foundation/CIPs/pull/749

Promoted to CPS candidate:
- https://github.com/cardano-foundation/CIPs/pull/625
- https://github.com/cardano-foundation/CIPs/pull/742

### CODE REVIEW

**Review by Ryun1 — APPROVED** [review]
LGTM 🤩

**Comment by Ryun1** [comment]
Should we give https://github.com/cardano-foundation/CIPs/pull/625 a number also?

**Comment by rphair** [comment]
> give https://github.com/cardano-foundation/CIPs/pull/625 a number also

@Ryun1 I would be happy to.  Everyone in this space is already using this document as a reference anyway, which effectively means it already _has_ been a candidate.  If no objections from @Crypto2099 I'll add it in this PR before merge.

**Review by Ryun1 — APPROVED** [review]

**Review by Crypto2099 — APPROVED** [review]
LGTM

**Pull request merged**
