### PR TITLE
CIP-0068 | Clarify label prefixes

### PR DESCRIPTION
**Pull request by mateusap1**
By reading the CIP-0068 and trying to implement it myself I was convinced the asset name should literally be prefixed with the label `(100)` and not with the implementation suggested by CIP-0067, there was no reference whatsoever to the correct label convention as far as I am aware and this PR tries to make things more clear for future developers attempting to implement CIP-0068 on their own.

### CODE REVIEW

**Comment by alessandrokonrad** [comment]
Thanks @mateusap1. This was indeed not very obvious. It wasn't clear back then how the labels will actually look like and then it was forgotten to specify them correctly in CIP-0068. However I think as a general convention and for convenience e.g. `(100)` could be a high level representation of an actual CIP-0067 label.

**Comment by mateusap1** [comment]
@alessandrokonrad Thanks for your quick reply.

> However I think as a general convention and for convenience e.g. (100) could be a high level representation of an actual CIP-0067 label.

I made a comment at the end of the "Labels" section trying to pass that idea. It reads as follows

> For simplicity purposes, the document will use the label `(100)` or `(<label>)` in the following documentation, but understand it should follow the CIP-0067 specification.

Let me know if this satisfies your concern or if you still have any suggestions / issues.

**Review by rphair — COMMENTED** [review]
Looks to me like the added text clarifies what was posted in comments so far, so I'd approve this as long as it satisfies @alessandrokonrad's latest comment & has no objections from @SmaugPool etc.

**Comment by alessandrokonrad** [comment]
@rphair yes this LGTM

**Review by rphair — APPROVED** [review]

**Review by KtorZ — APPROVED** [review]

**Pull request merged**
