### PR TITLE
CIP-0010 | Add 10297 label for fida.finance

### PR DESCRIPTION
**Pull request by ssledz**

### CODE REVIEW

**Comment by rphair** [comment]
@ssledz - Would you please edit your submission so the metadata number is sorted in correct numerical order with the other submissions and correct the mismatch in indentation?

@Ryun1 @Crypto2099 @perturbing certainly this looks justified: https://medium.com/@fida.finance/democratizing-the-insurance-industry-through-blockchain-990700fd438f

... but maybe we should wait to ensure the request is properly formatted before enabling the new GitHub CI processing of CIP-0010 additions.  I'm not sure if it checks for proper numerical order and/or sorts them (cc @Godspeed-exe from https://github.com/cardano-foundation/CIPs/pull/837).

**Comment by Godspeed-exe** [comment]
@rphair my workflow does not check for sorting / do sorting.

**Comment by perturbing** [comment]
@rphair, my view of this CIP is that currently any project can claim a label number. So with that, I think this PR indeed looks justified by your above link.

That said, I do wonder how this will pan out in the future, as there is no clear guideline. Furthermore, currently labels are forever, are all registered labels still actively used? These two things might cause some issues in the future, where we as CIP editors do not have clear guidance.

**Comment by rphair** [comment]
Yes @perturbing - I agree on all of that & think that CIP-0010 might benefit from an update with whatever clarification might be necessary as project tag requests start coming in again.

One more issue is the human factor that, because of their sorted arrangement, these aren't just cardinal numbers as the CIP indicates but are also perceived as _ordinal_ numbers.  This has the interesting consequence that those apparently taking advantage of that ordinality will also be the least likely to acknowledge it:

* https://github.com/cardano-foundation/CIPs/pull/799

... so perhaps this dialogue could also be considered in a CIP-0010 update that provides guidelines to establish project _significance_ in numbering, as well as proof of legitimacy.

@ssledz this is just a side discussion to your submission & rest assured we will enable the GitHub CI workflow on this PR as soon as you clean up your edited file as requested.

**Comment by perturbing** [comment]
Just a little brainstorm :) 

1) I think one addition to CIP-010 could be the addition of the test that there is a  reasonal change that others (people/tooling etc) observing this metadata might want clarity. For example, any project that has an app where users connect their wallet, the wallets might want to leverage the knowledge of this CIP. But applications that are isolated (for whatever reason), do not (liquidation on a lending protocol for example).

2). We could hash (even with a VRF if needed for proper randomness), their PR, and modulo reduce it to fit in the range and have that as their number

**Review by rphair — APPROVED** [review]
@ssledz I've done the edits that we asked you to do and @Ryun1 will open up issues for the general questions that have come up here.

@perturbing @Crypto2099 apparently this edit has triggered the GitHub CI and it looks like it's passed already.  This is ready for merge but since it's our first CI workflow run for the CIP-0010 structure I guess we should check those workflow logs. 🤔

**Comment by Ryun1** [comment]
Issue to continue discussions!
https://github.com/cardano-foundation/CIPs/issues/914

**Review by Ryun1 — APPROVED** [review]

**Comment by ssledz** [comment]
@rphair thanks for handling this I have just missed this pr & conversation in the rush of tasks 😅

**Pull request merged**
