### PR TITLE
CIP-1852: fix broken CIP links

### PR DESCRIPTION
**Pull request by ciphero**

### CODE REVIEW

**Comment by rphair** [comment]
@ciphero in what context do the relative paths for these links appear broken?

**Comment by ciphero** [comment]
> @ciphero in what context do the relative paths for these links appear broken?

They're broken on the website: https://cips.cardano.org/cips/cip1852/

**Comment by rphair** [comment]
There's something more complicated here than just changing a relative pathname.  I was about to suggest (@katomm) that cips.cardano.org might be deprecated in favour of the Developer Portal pages when I noticed, e.g. on this page: https://developers.cardano.org/docs/governance/cardano-improvement-proposals/CIP-1852
- When I go to the CIP-1852 dev portal page directly, its links to CIP3 are invalid: https://developers.cardano.org/docs/governance/cardano-improvement-proposals/cip-1852/CIP-0003
- But if I visit the CIP-0003 dev portal page first (https://developers.cardano.org/docs/governance/cardano-improvement-proposals/CIP-0003), and then go to CIP-1852 from the left nav sidebar, the link is correct: https://developers.cardano.org/docs/governance/cardano-improvement-proposals/CIP-0003
- I can reproduce the problem repeatedly by flushing the cache for the CIP-1852 page & revisiting it.  Every time, the link for CIP3 is broken until that page itself is visited first.

@crptmppt @ktorz I know all these relative paths were recently rationalised but perhaps someone with more Github Pages experience could check out why the above anomaly happens before deciding how to correct individual cross-CIP links?

**Comment by katomm** [comment]
Thanks for flagging @rphair. No worries, this looks like a problem caused by the developer portal, not by the cips repo. I'll take care of it after the holidays.

**Comment by ciphero** [comment]
Some of the CIP links in CIP-1852 are absolute refs others are relative. Since the ones that are not working are relative I created the PR to normalise the configuration to what was working i.e. absolute URI path, e.g. ref link: CIP-1854.
Is it documented somewhere how this should be configured? Thanks

**Comment by KtorZ** [comment]
I have been steadily converting all URLs to absolute URLs. I did a first batch some weeks ago but haven't yet done all. Some links are also dead, I started listing them with a tool but didn't yet proceed to update.

Perhaps we could mention this on the CIP-0001 and pay more attention during editors review. Ideally, I'd like this to be automatically checked by some form of CI workflow.

**Review by crptmppt — APPROVED** [review]

**Review by KtorZ — APPROVED** [review]

**Pull request merged**
