### PR TITLE
CIP-0016 | Adjust preamble and structure w.r.t CIP-0001

### LINKED ISSUE #659: CIP-0016 | Adjust preamble and structure w.r.t CIP-0001
Fixed by #660.

### PR DESCRIPTION
**Pull request by rphair**
Fixes #659.

([edited proposal](https://github.com/rphair/CIPs/blob/remediate-0016/CIP-0016/README.md))

### CODE REVIEW

**Comment by rphair** [comment]
@intricate although this was merged as `Active` I didn't see that any commercial or community implementations were indicated in the linked discussion, nor could I find any today.

Since the CIP as merged didn't have anything like a _Path to Active_ indicating progress that would have validated it as `Active`, I've reset the status to `Proposed`.

Perhaps it was given `Active` status based on expectation or as a formality.  If you or anyone else know implementations of this proposed standard then please let us know.

**Review by Ryun1 — COMMENTED** [review]
> or anyone else know implementations of this proposed standard

I think [jcli](https://github.com/input-output-hk/catalyst-core/tree/main/src/jormungandr/jcli), [cardano-signer](https://github.com/gitmachtl/cardano-signer) and [CSL](https://github.com/Emurgo/cardano-serialization-lib) support these formats.

**Comment by rphair** [comment]
That's why we need you @Ryun1 😎 ... resetting back to `Active` status with proper documentation of current implementations as you've indicated.

Also I realised in hindsight that CIP-0001 allows `N/A` for an Implementation Plan which I think is appropriate when real-world implementations precede or substitute a designated reference implementation... so I've also set that in this typical case.

**Review by Ryun1 — APPROVED** [review]
> That's why we need you @Ryun1 😎 ... resetting back to Active status with proper documentation of current implementations as you've indicated.

This is why we are a team!

**Review by Crypto2099 — APPROVED** [review]
LGTM

**Pull request merged**
