### PR TITLE
Proposed new CIP-101????

### PR DESCRIPTION
**Pull request by johnnygreeney**
Proposed new CIP number 101 (or 404). A to Z Glossary of Cardano. See README.md, should be self-explanatory

### CODE REVIEW

**Comment by rphair** [comment]
This is perhaps some useful material but it is absolutely not a suitable subject for a CIP.  I would recommend formatting it as a web or GitHub document page and submitting it here: https://github.com/input-output-hk/essential-cardano

**Comment by rphair** [comment]
Good work 🤓

**Comment by NetWalker108** [comment]
@rphair why is this not a suitable subject as a CIP, especially an informational CIP?

**Comment by rphair** [comment]
It does not describe an _improvement_ to Cardano; therefore it is not a Cardano _Improvement_ Proposal.  Improvements are defined as _designs_ (see beginning of [CIP-0001](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0001/README.md)) and there is no design in a glossary or any other mundane set of facts or descriptions.

BTW the term "Informational" CIP is obsolete.  `Informational` used to be a valid `Type` field, but that field and all its contents have not been assigned to new CIPs for quite some time and they'll be removed from old CIPs in the upcoming months.  CIPs classified as "Informational" were also about designs but documented after the designs were produced (hence not subject to so much debate).

**Comment by NetWalker108** [comment]
> BTW the term "Informational" CIP is obsolete.  Informational used to be a valid Type field, but that field and all its contents have not been assigned to new CIPs for quite some time and they'll be removed from old CIPs in the upcoming months.

This is a very odd and rather backwards approach that's being used for the CIP process. 

@KtorZ @Crypto2099 you all approved this?

**Pull request closed without merging**
