### PR TITLE
Crypto2099 Information and Voting Reservation

### PR DESCRIPTION
**Pull request by Crypto2099**
Reserving entries for:
1. Informational metadata post (Key 411) which should generally take the format of an array of string
2. Crypto2099 On-Chain Voting Mechanism keys for Ballot Proposal, Voter Registration/Identification Information, and Voter Ballots.

### CODE REVIEW

**Comment by mmahut** [comment]
Can you please elaborate on "General information metadata"?

**Comment by Crypto2099** [comment]
> Can you please elaborate on "General information metadata"?

I have used this index, as have other including Andrew Westberg and more, to submit "general" metadata information to document on-chain. **411** was the old telephone prefix in the United States to dial "information" and the concept here was to reserve a documented index to use for these.

The format is designed to be an array of strings that can be recompiled into a cohesive piece of text, utilizing an empty string entry as a "paragraph break".

Example:
```json
{
  "411": [
      "This is line one of my information...",
      "it wraps around to another line because the first line is >64char",
      "",
      "This is a new paragraph.",
    ]
}
```

**Comment by crptmppt** [comment]
@Crypto2099 Hi! Can you resolve the conflicts / rebase the branch?

**Comment by Crypto2099** [comment]
Closing this one in favor of https://github.com/cardano-foundation/CIPs/pull/80 which follows the new format.

**Pull request closed without merging**
