### PR TITLE
CIP-1694 | French - Clarify note on info actions

### PR DESCRIPTION
**Pull request by Hornan7**
- Correction to the french version related to PR #834
- Complete audit of the French version
- Modification and preservation of terms that are machine readable. ex: Yes, No, Abstain
- Correction of erroneous and confusing term such as "mesure de gouvernance" and "mise"
- Fixed several turns of phrase in a better French.

### CODE REVIEW

**Comment by Hornan7** [comment]
During the audit of the French version I noticed some small updates which in my opinion would be important to make to the original version in order to avoid possible (additional) confusion within the community. Can I report them to you here, or would it be better to create an Issue? or another pull request to make these fixes?

**Comment by rphair** [comment]
> small updates which in my opinion would be important to make to the english version in order to avoid possible (additional) confusion within the community. Can I report them to you here, or would it be better to create an Issue? or another pull request

@Hornan7 I think it would be better to put in a pull request ASAP since as you have noted from https://github.com/cardano-foundation/CIPs/pull/800 @WhatisRT @lehins are finalising this document in anticipation of the governance launch, so it would be better to get their & community attention immediately on any remaining possible problems.

**Review by rphair — APPROVED** [review]
The audit in addition to https://github.com/cardano-foundation/CIPs/pull/834 looks comprehensive: I can tell these kinds of changes are for reading fluency for native speakers as well as canonical Cardano & blockchain terminology in French.  Thanks again 🎉

**Comment by WhatisRT** [comment]
Yes, a PR would be very welcome!

**Comment by Hornan7** [comment]
Alright, I will have it ready today. 😃👍

**Comment by Hornan7** [comment]
I will close this pull request for now to prioritize the one for the original file. If accepted, I will then proceed to make the necessary modifications to the French version

**Pull request closed without merging**
